# Generated by Django 4.2.19 on 2025-03-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gender_id',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='iin',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
