# Generated by Django 4.2.19 on 2025-03-04 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('iin', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('father_name', models.CharField(max_length=256)),
                ('b_day', models.DateField()),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gender')),
            ],
        ),
    ]
