# Generated by Django 4.2.19 on 2025-03-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0024_alter_atec_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGuideSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('test_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='results.testtypes')),
            ],
        ),
    ]
